CREATE TABLE hgj_user(
    USER_ID          	VARCHAR(50) NOT NULL,
    USER_NAME        	VARCHAR(50) NOT NULL,
    LOGIN_NAME    	VARCHAR(50) NOT NULL,
    PASSWORD       VARCHAR(50) NOT NULL,
    USER_MAIL       	VARCHAR(50) NOT NULL,
    LOGIN_FAIL_TIME     DATETIME ,
    PRIMARY KEY (USER_ID),
    UNIQUE INDEX UNIQUE_HGJ_USER_LOGIN_NAME(LOGIN_NAME)
)ENGINE=INNODB;